server:
  servlet:
    context-path: /api

spring:
 application:
  name: servico-cliente-ms

 datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/clientemsdb?currentSchema=public}
    username: ${DATASOURCE_USER:postgres}
    password: ${DATASOURCE_PASS:postgres}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: SpringBootJPAHikariCP
      minimumIdle: 15
      maximumPoolSize: 50
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 1000000

 thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  cache: false
  mode: HTML
  encoding: UTF-8
  servlet:
   content-type: text/html
 web:
  resources:
   static-locations: classpath:/static/ 
     
z-api:
  instancia-id: ${Z_API_INSTANCIA_ID:1234567}
  token-instancia: ${Z_API_TOKEN_INSTANCIA:1234567}
  token-cliente: ${Z_API_TOKEN_CLIENTE:1234567}

discord:
  channel:
    id: ${ID_CHANNEL_DISCORD:123456}
  bot:
    token: ${DISCORD_TOKEN:bot234567}

aws:
  url: ${AWS_URL:http://localhost:8080}
