server:
  servlet:
    context-path: /api

spring:
 application:
  name: servico-cliente-ms

 datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/clientemsdb?currentSchema=public}
    username: ${DATASOURCE_USER:postgres}
    password: ${DATASOURCE_PASS:postgres}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: SpringBootJPAHikariCP
      minimumIdle: 15
      maximumPoolSize: 50
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 1000000

 thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  cache: false
  mode: HTML
  encoding: UTF-8
  servlet:
   content-type: text/html
 web:
  resources:
   static-locations: classpath:/static/ 
     
z-api:
  instancia-id: ${Z_API_INSTANCIA_ID:1234567}
  token-instancia: ${Z_API_TOKEN_INSTANCIA:1234567}
  token-cliente: ${Z_API_TOKEN_CLIENTE:1234567}

aws:
  url: ${AWS_URL:http://localhost:8080}

discord:
  api-url: https://discord.com
  bot:
    token: ${DISCORD_TOKEN:1234567}
  guild-wakanda:
    id: ${DISCORD_GUILD_ID:1234567}
  channels:
    id: ${DISCORD_ID_CHANNEL:1234567}    
    validacao: ${DISCORD_ID_CANAL_VALIDACAO:1234567}
    falha: ${DISCORD_ID_CANAL_FALHA:1234567}
    iniciar-validacao: ${DISCORD_ID_CANAL_INICIAR_VALIDACAO:1234567}
  roles:
    membro-validado: ${DISCORD_ID_CARGO_MEMBRO_VALIDADO:1234567}
    default-role: ${DISCORD_ID_CARGO_DEFAULT:1234567}
    wakander: ${DISCORD_ID_CARGO_WAKANDER:1234567}
    falha: ${DISCORD_ID_CARGO_FALHA:1234567}
    membro-cancelado: ${DISCORD_ID_CARGO_CANCELADO:1234567}